DROP TABLE INVENTORY CASCADE CONSTRAINTS;

CREATE TABLE INVENTORY(
	ProductID Integer NOT NULL,
	ProductDesc VarChar(30),
	ProductPrice Numeric(8,2),
	ProductStockAmount Integer,
	PRIMARY KEY (ProductID)
);

DROP TABLE ORDERS CASCADE CONSTRAINTS;

CREATE TABLE ORDERS(
	OrderID Integer NOT NULL,
	OrderType VarChar(30), --Could make a single character with key
	OrderCompleted Integer, --Could use smaller number format or char
	OrderPlaced Date,
	PRIMARY KEY (OrderID)
);

DROP TABLE ORDER_PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE ORDER_PRODUCTS(
	OrderID Integer NOT NULL,
	ProductID Integer NOT NULL,
	ProductQuantity Integer,
	PRIMARY KEY (OrderID, ProductID),
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES INVENTORY(ProductID) ON DELETE CASCADE
);

DROP TABLE DELIVERIES CASCADE CONSTRAINTS;

CREATE TABLE DELIVERIES(
	OrderID Integer NOT NULL,
	FName VarChar(30), --Could store customer data in separate table (normalisation)
	LName VarChar(30),
	House VarChar(30),
	Street VarChar(30),
	City VarChar(30),
	DeliveryDate Date,
	PRIMARY KEY (OrderID),
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE
);

DROP TABLE COLLECTIONS CASCADE CONSTRAINTS;

CREATE TABLE COLLECTIONS(
	OrderID Integer NOT NULL,
	FName VarChar(30),
	LName VarChar(30),
	CollectionDate Date,
	PRIMARY KEY (OrderID),
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE
);

DROP TABLE STAFF CASCADE CONSTRAINTS;

CREATE TABLE STAFF(
	StaffID Integer NOT NULL,
	FName VarChar(30),
	LName VarChar(30),
	PRIMARY KEY (StaffID)
);

DROP TABLE STAFF_ORDERS CASCADE CONSTRAINTS;

CREATE TABLE STAFF_ORDERS(
	StaffID Integer NOT NULL,
	OrderID Integer NOT NULL,
	PRIMARY KEY (StaffID, OrderID),
	FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE CASCADE,
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE
);

DROP SEQUENCE product_seq;
DROP SEQUENCE order_seq;
DROP SEQUENCE staff_seq;

CREATE SEQUENCE product_seq START WITH 1;
CREATE SEQUENCE order_seq START WITH 1;
CREATE SEQUENCE staff_seq START WITH 1;

CREATE OR REPLACE TRIGGER product_inc
	BEFORE INSERT ON INVENTORY
	FOR EACH ROW

	BEGIN
		:new.ProductID := product_seq.NEXTVAL;
	END;
/

CREATE OR REPLACE TRIGGER order_inc
	BEFORE INSERT ON ORDERS
	FOR EACH ROW

	BEGIN
		:new.OrderID := order_seq.NEXTVAL;
	END;
/

CREATE OR REPLACE TRIGGER staff_inc
	BEFORE INSERT ON STAFF
	FOR EACH ROW

	BEGIN
		:new.StaffID := staff_seq.NEXTVAL;
	END;
/
